name: Download Cloudflared Binary

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: '0 0 * * 0'  # optional: every Sunday to update binary

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download latest Cloudflared binary
        run: |
          curl -L -o cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared

      - name: Commit & push to repo
        run: git add .
      - name: Commit change to repo
        run: git -c user.email="${{ secrets.EMAIL }}" -c user.name="${{ secrets.USERNAME }}" commit -am "Add 1st file again"
      - name: Push change to repo
        run: git push origin main
